require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'App_name' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'App_nameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
   # flipper_post_install(installer)
  #end
end

target 'App_name-tvOS' do
  # Pods for jssip634-tvOS

  target 'App_name-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
